- name: ponomar_course
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Install python
      apt:
        name: python
        state: latest 
        force: yes
        force_apt_get: yes
        update_cache: yes


    - name: Install iptables
      apt:
        name: iptables
        state: latest

    - name: Install lvm2
      apt: 
        name: lvm2
        state: latest 

    - name: Set up the repository
      apt: 
        name: apt-transport-https

    - name: Set up the repository
      apt: 
        name: ca-certificates

    - name: Set up the repository
      apt: 
        name: curl

    - name: Set up the repository
      apt: 
        name: gnupg

    - name: Set up the repository
      apt: 
        name: lsb-release




    

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: yes